name: Sonar scan

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    uses: genesislcap/platform-releases/.github/workflows/product-gradle-sonar-scan.yaml@master
    with:
      repository: genesislcap/genesis-symphony
    secrets:
      JFROG_RO_USER : ${{ secrets.JFROG_RO_USER }}
      JFROG_RO_PASSWORD : ${{ secrets.JFROG_RO_PASSWORD }}
      SONAR_TOKEN : ${{ secrets.JENKINSGENESIS_SONAR }}
